### ISSUE TITLE
Example for the ambient.csv and pipe.csv

### ISSUE THREAD

**Issue by ivicajan** [pnsaevik/effluent#52]
Der developer,
would  it be possible to add an example of the csv files so it is easier to construct realitstic test case?
Just a few depths for example of ambient csv file should be OK, similar for pipe.csv.

Is it possible to use direct Xarray object as an input (thinking of ambient object) for the model run directly inside python/notebook? Example (notebok) would be great.

Thanks in advance

Regards
Ivica

**Comment by pnsaevik** [comment]
Sorry for the late response. I agree that a csv example would be good to have. For instance, I can convert the "stratified" example to a csv-based configuration.

It is possible to use xarray directly. The feature is poorly documented, since I still want to keep the possibility of changing the internal API in the near future. But you may have a look at the internal API reference at https://effluent.readthedocs.io/en/latest/autoapi/index.html. The procedure is (currently) as follows:

1. Create a `config` dict containing the configuration (as otherwise specified in the `.toml` file)
2. Initialize a `model` object using the method `effluent.model.Model.from_config`
3. Initialize a custom `ambient` object using `effluent.io.AmbientXarray`
4. Set the attribute `model.ambient` to the newly created `ambient` object

Suggestions for a better internal API for this task is welcome. Regarding the csv example, I should be able to look at it in a few weeks.
